llm:
  provider: OPENROUTER
  meta:
    model: openai/gpt-oss-20b:free
    max_tokens: 1500
    temperature: 0.2
  http_client:
    api_url: https://openrouter.ai/api/v1
    api_token: ${OPENROUTER_API_KEY}   # подтянется из секретов CI/локального окружения

vcs:
  provider: GITHUB

review:
  mode: ONLY_ADDED_WITH_CONTEXT
  context_lines: 6
  ignore_changes: ["docs/**", "**/*.md", "**/*.png", "**/*.svg"]

logger:
  level: INFO
